[package]
name = "linutil-egui"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
eframe = "0.29"
egui = "0.29"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
linutil_core = { path = "../core" }